import React from 'react';
// import './Menu.css';

const Menu = () => {
    return (
     
    <div className="App">
      <button className="botonMenu">Inicio</button>
    <div style={{height: 'auto', borderTop: '2px solid rgb(204, 204, 204)', borderBottom: '2px solid rgb(204, 204, 204)', minHeight: '100%', opacity: 1, visibility: 'visible', right: '0px', top: '0px', backgroundColor: 'rgb(248, 248, 248)', color: 'rgb(0, 0, 0)', float: 'none', padding: '18px 20px 0px', width: '77%', position: 'absolute', display: 'block', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}>
    <a href="https://www.ilumitec.es/mecanismos" style={{backgroundColor: 'rgb(248, 248, 248)', color: 'rgb(85, 85, 85)', borderLeft: '3px solid rgb(255, 105, 5)', fontSize: '16px', fontWeight: 700, textDecoration: 'none solid rgb(85, 85, 85)', display: 'block', padding: '16px 11px', borderBottom: '1px solid rgb(229, 229, 229)', width: '23%', float: 'left', position: 'relative', outline: 'rgb(85, 85, 85) none 0px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', outlineOffset: '-2px'}}> Mecanismos</a>
    <ul style={{margin: '0px 0px 20px', width: '25%', padding: '0px 20px 0px 0px', textAlign: 'left', float: 'left', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased', marginBottom: '20px', marginTop: '0px'}}>
        <li style={{padding: '8px 10px 5px 0px', color: 'rgb(51, 51, 51)', borderBottom: '1px solid rgb(204, 204, 204)', lineHeight: 'normal', width: '100%', listStyle: 'outside none none', display: 'block', fontSize: '11px', fontWeight: 700, marginBottom: '7px', textTransform: 'uppercase', letterSpacing: '1px', boxSizing: 'border-box', textDecoration: 'none solid rgb(51, 51, 51)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/mecanismos-simon" style={{color: 'rgb(51, 51, 51)', fontSize: '14px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Mecanismos Simon</a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-82" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon 82 </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-82-nature" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon 82 Nature </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-detail-82" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon Detail 82 </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-82-concept" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon 82 Concept </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-27" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon 27 Play y Neos </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-100" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon 100 </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-270" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon 270 </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-31" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon 31 </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-75" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon 75 </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-73-loft" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon 73 Loft </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-44-aqua" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon 44 AQUA </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/simon-500-cima" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Simon 500 CIMA </a></li>
    </ul>
    <ul style={{margin: '0px 0px 20px', width: '25%', padding: '0px 20px 0px 0px', textAlign: 'left', float: 'left', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased', marginBottom: '20px', marginTop: '0px'}}>
        <li style={{padding: '8px 10px 5px 0px', color: 'rgb(51, 51, 51)', borderBottom: '1px solid rgb(204, 204, 204)', lineHeight: 'normal', width: '100%', listStyle: 'outside none none', display: 'block', fontSize: '11px', fontWeight: 700, marginBottom: '7px', textTransform: 'uppercase', letterSpacing: '1px', boxSizing: 'border-box', textDecoration: 'none solid rgb(51, 51, 51)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/mecanismos-niessen-abb" style={{color: 'rgb(51, 51, 51)', fontSize: '14px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Mecanismos Niessen ABB</a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/niessen-zenit" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Niessen Zenit </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/niessen-sky" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Niessen Sky </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/niessen-skymoon" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Niessen SkyMoon </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/niessen-olas" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Niessen Olas </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/niessen-arco" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Niessen Arco </a></li>
    </ul>
    <div style={{boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased', display: 'none'}}></div>
    <ul style={{margin: '0px 0px 20px', width: '25%', padding: '0px 20px 0px 0px', textAlign: 'left', float: 'left', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased', marginBottom: '20px', marginTop: '0px'}}>
        <li style={{padding: '8px 10px 5px 0px', color: 'rgb(51, 51, 51)', borderBottom: '1px solid rgb(204, 204, 204)', lineHeight: 'normal', width: '100%', listStyle: 'outside none none', display: 'block', fontSize: '11px', fontWeight: 700, marginBottom: '7px', textTransform: 'uppercase', letterSpacing: '1px', boxSizing: 'border-box', textDecoration: 'none solid rgb(51, 51, 51)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/mecanismos-schneider" style={{color: 'rgb(51, 51, 51)', fontSize: '14px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Mecanismos Schneider</a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/schneider-new-unica" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Schneider New Unica </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/schneider-elegance" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Schneider Elegance </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/schneider-d-life" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Schneider D-Life </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/schneider-mureva-styl" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Schneider Mureva Styl </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/schneider-sedna" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Schneider Sedna </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/unica-top" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Schneider Unica Top </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/unica-plus" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Schneider UNICA Plus / Basic / Colors </a></li>
    </ul>
    <ul style={{margin: '0px 0px 20px', width: '25%', padding: '0px 20px 0px 0px', textAlign: 'left', float: 'left', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased', marginBottom: '20px', marginTop: '0px'}}>
        <li style={{padding: '8px 10px 5px 0px', color: 'rgb(51, 51, 51)', borderBottom: '1px solid rgb(204, 204, 204)', lineHeight: 'normal', width: '100%', listStyle: 'outside none none', display: 'block', fontSize: '11px', fontWeight: 700, marginBottom: '7px', textTransform: 'uppercase', letterSpacing: '1px', boxSizing: 'border-box', textDecoration: 'none solid rgb(51, 51, 51)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/mecanismos-legrand" style={{color: 'rgb(51, 51, 51)', fontSize: '14px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Mecanismos Legrand</a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/legrand-niloe-step" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Legrand Niloé Step </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/legrand-valena-next" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Legrand Valena Next </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/legrand-plexo" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Legrand Plexo </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/legrand-niloe" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Legrand Niloé </a></li>
    </ul>
    <div style={{boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}></div>
    <ul style={{margin: '0px 0px 20px', width: '25%', padding: '0px 20px 0px 0px', textAlign: 'left', float: 'left', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased', marginBottom: '20px', marginTop: '0px'}}>
        <li style={{padding: '8px 10px 5px 0px', color: 'rgb(51, 51, 51)', borderBottom: '1px solid rgb(204, 204, 204)', lineHeight: 'normal', width: '100%', listStyle: 'outside none none', display: 'block', fontSize: '11px', fontWeight: 700, marginBottom: '7px', textTransform: 'uppercase', letterSpacing: '1px', boxSizing: 'border-box', textDecoration: 'none solid rgb(51, 51, 51)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/mecanismos-bticino" style={{color: 'rgb(51, 51, 51)', fontSize: '14px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Mecanismos Bticino</a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/bticino-living-light" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Bticino Living Light </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/bticino-living-now" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Bticino Living Now </a></li>
    </ul>
    <ul style={{margin: '0px 0px 20px', width: '25%', padding: '0px 20px 0px 0px', textAlign: 'left', float: 'left', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased', marginBottom: '20px', marginTop: '0px'}}>
        <li style={{padding: '8px 10px 5px 0px', color: 'rgb(51, 51, 51)', borderBottom: '1px solid rgb(204, 204, 204)', lineHeight: 'normal', width: '100%', listStyle: 'outside none none', display: 'block', fontSize: '11px', fontWeight: 700, marginBottom: '7px', textTransform: 'uppercase', letterSpacing: '1px', boxSizing: 'border-box', textDecoration: 'none solid rgb(51, 51, 51)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/mecanismos-jung" style={{color: 'rgb(51, 51, 51)', fontSize: '14px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Mecanismos Jung</a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/jung-ls990" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Jung LS990 </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/jung-ls-plus" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Jung LS PLUS </a></li>
        <li style={{width: '100%', listStyle: 'outside none none', lineHeight: '24px', boxSizing: 'border-box', textDecoration: 'none solid rgb(0, 0, 0)', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.ilumitec.es/jung-ls-design" style={{textTransform: 'none', fontSize: '13px', letterSpacing: 'normal', color: 'rgb(51, 51, 51)', textDecoration: 'none solid rgb(51, 51, 51)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', backgroundColor: 'rgba(0, 0, 0, 0)'}}>Jung LS Design </a></li>
    </ul>
</div>
</div>
  );
    }
export default Menu;